<%@ Page Language="C#" AutoEventWireup="true" EnableEventValidation="false" MasterPageFile="~/Site.master" CodeBehind="NewAdminCDB.aspx.cs" Inherits="Mitchell.ScmConsoles.NewCDBConsole.NewAdminCDB" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>


<asp:Content ID="BodyContent" ContentPlaceHolderID="ConsoleContent" runat="server"> 
    <style></style>
    
<style >
    .grid {
        overflow: auto;    }

    body {
   min-height: 100%;
}

</style>
      <h1 style="box-sizing: border-box; margin: 20px 0px 10px; font-size: 36px; font-family: &quot;Open Sans&quot;, Arial, helvitica, sans-serif; font-weight: 500; line-height: 1.1; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">SCM<span>&nbsp;</span><small style="box-sizing: border-box; font-size: 23.4px; font-weight: 400; line-height: 1; color: rgb(119, 119, 119);">Admin CDB Console</small></h1>
        <div>
            <asp:Panel ID="View1" runat="server">


                
                <telerik:RadGrid ID="RadGrid1" runat="server" AllowFilteringByColumn="True" AllowSorting="True" AutoGenerateDeleteColumn="True" Width="100%" BorderWidth="1px"
                    HeaderStyle-HorizontalAlign="Left" HeaderStyle-VerticalAlign="Top" 
                    GroupPanelPosition="Top" OnDeleteCommand="RadGrid1_ItemCommand" OnInsertCommand="RadGrid1_InsertCommand" AutoGenerateEditColumn="True" CellSpacing="-1" GridLines="Both" AllowPaging="True" OnUpdateCommand="RadGrid1_UpdateCommand" AllowAutomaticInserts="True" AllowMultiRowEdit="True" ViewStateMode="Enabled" Skin="Bootstrap">

                    <MasterTableView CommandItemDisplay="Top" DataKeyNames="seq_id" >
                        <CommandItemSettings ShowAddNewRecordButton="false" />
                        <Columns>
                            
                            <telerik:GridTemplateColumn Display="false">
                                <ItemTemplate>
                                    <asp:HiddenField ID="hdnSeqID" runat="server" Value='<%# Eval("seq_id") %>' />
                                    <asp:HiddenField ID="hdnServerName" runat="server" Value='<%# Eval("ServerName") %>' />
                                </ItemTemplate>

                            </telerik:GridTemplateColumn>
                        </Columns>
                    </MasterTableView>



                    <EditItemStyle BorderStyle="Double" />
                    <HeaderStyle HorizontalAlign="Left" VerticalAlign="Top" />



                </telerik:RadGrid>
                <asp:Button ID="btnAddNew" runat="server" Text="Add New Record" OnClick="btnAddNew_Click" />


                <asp:LinkButton ID="linkDecommisoen" runat="server" OnClick="linkDecommisoen_Click">Decommisoned Servers</asp:LinkButton>
                &nbsp;&nbsp;&nbsp;
                <asp:LinkButton ID="linkOldCDB" runat="server" OnClick="linkOldCDB_Click">Go To Old CDB Admin Page</asp:LinkButton>
                &nbsp;


            </asp:Panel>
            <asp:Panel ID="View2" runat="server">
                <br />
                <h1>Add New Servers</h1>
                <asp:Table ID="tblAdd" runat="server" Height="114" Width="439">
                </asp:Table>
                <asp:Button ID="btnInsert" runat="server" Text="Insert Record" OnClick="btnInsert_Click" />

            </asp:Panel>


        </div>
   

    </asp:Content>